{
 "title": "Custom disk performance - V2",
 "description": "Dashboard to view multiple servers",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_exporter_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk IO Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node_health\"}[5m]) / rate(node_disk_reads_completed_total{job=\"node_health\"}[5m]) or irate(node_disk_read_bytes_total{job=\"node_health\"}[5m]) / irate(node_disk_reads_completed_total{job=\"node_health\"}[5m]) "
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node_health\"}[5m]) * 512 / rate(node_disk_writes_completed_total{job=\"node_health\"}[5m]) or irate(node_disk_written_bytes_total{job=\"node_health\"}[5m]) / irate(node_disk_writes_completed_total{job=\"node_health\"}[5m]) "
    }
   ]
  },
  {
   "title": "Disk Operations Merge Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(1 + rate(node_disk_reads_merged_total{job=\"node_health\"}[5m]) / rate(node_disk_reads_completed_total{job=\"node_health\"}[5m])) or (1 + irate(node_disk_reads_merged_total{job=\"node_health\"}[5m]) / irate(node_disk_reads_completed_total{job=\"node_health\"}[5m]))"
    },
    {
     "expr": "(1 + rate(node_disk_writes_merged_total{job=\"node_health\"}[5m]) / rate(node_disk_writes_completed_total{job=\"node_health\"}[5m])) or (1 + irate(node_disk_writes_merged_total{job=\"node_health\"}[5m]) / irate(node_disk_writes_completed_total{job=\"node_health\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node_health\"}[5m])/1000 or \nirate(node_disk_io_time_seconds_total{job=\"node_health\"}[5m])/1000"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{job=\"node_health\"}[5m])/1000 or irate(node_disk_read_time_seconds_total{job=\"node_health\"}[5m])/1000"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{job=\"node_health\"}[5m])/1000 or irate(node_disk_write_time_seconds_total{job=\"node_health\"}[5m])/1000"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(rate(node_disk_read_bytes_total{job=\"node_health\"}[5m]) or \nirate(node_disk_read_bytes_total{job=\"node_health\"}[5m]))"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node_health\"}[5m]) or \nirate(node_disk_written_bytes_total{job=\"node_health\"}[5m])"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(rate(node_disk_reads_completed_total{device=\"dm-0\", job=\"node_health\"}[5m]) or \nirate(node_disk_reads_completed_total{job=\"node_health\"}[5m]))"
    },
    {
     "expr": "(rate(node_disk_writes_completed_total{job=\"node_health\"}[5m]) or \nirate(node_disk_writes_completed_total{job=\"node_health\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "(rate(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"node_health\"}[5m]) / \nrate(node_disk_reads_completed_total{device=~\"$device\", job=\"node_health\"}[5m])) or \n(irate(node_disk_read_time_seconds_total{device=~\"$device\", job=~\"node_health\"}[5m]) / \nirate(node_disk_reads_completed_total{device=~\"$device\", job=~\"node_health\"}[5m]))"
    }
   ]
  },
  { "title": "$node", "type": "text", "gridPos": { "h": 3, "w": 8, "x": 0, "y": 56 }, "repeat": "node" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"system\",instance=~'$node'}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"user\",instance=~'$node'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"idle\",instance=~'$node'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"guest\",instance=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  }
 ]
}