{
 "title": "192.168.42.102 MongoDB Wired Tiger",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "192.168.42.102:9216" },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Wired Tiger Cache Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=\"$host\",type=\"total\"}"
    }
   ]
  },
  {
   "title": "Wired Tiger Max Cache Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=\"192.168.42.102:9100\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"192.168.42.102:9100\"}"
    }
   ]
  },
  {
   "title": "WiredTiger Transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_transactions_total{instance=\"192.168.42.102:9216\", type=~\"(begins|checkpoints|committed|rolledback)\"}[$interval]) or \nirate(mongodb_mongod_wiredtiger_transactions_total{instance=\"192.168.42.102:9216\", type=~\"(begins|checkpoints|committed|rolledback)\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Activity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Block Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{instance=\"$host\", type=~\"(read|written)\"}[$interval]) or \nirate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{instance=\"$host\", type=~\"(read|written)\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_cursors_total{instance=\"$host\"}",
     "legendFormat": "Cursors"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_sessions_total{instance=\"$host\"}",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "WiredTiger Concurrency Tickets Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Checkpoint Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{instance=\"$host\"}[5m])",
     "legendFormat": "current"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{instance=\"$host\", type=~\"(max|min)\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Eviction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Pages / sec" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=\"$host\"}[$interval]) or \nirate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{instance=\"$host\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=\"$host\", type=\"total\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Pages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_pages{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_operations_total{instance=\"$host\"}[$interval]) or \nirate(mongodb_mongod_wiredtiger_log_operations_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_bytes_total{instance=\"$host\"}[$interval]) or \nirate(mongodb_mongod_wiredtiger_log_bytes_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_records_total{instance=\"$host\"}[$interval]) or \nirate(mongodb_mongod_wiredtiger_log_records_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=~\"(delete|insert|update)\"}[$interval]) or \nirate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=~\"(delete|insert|update)\"}[5m])",
     "legendFormat": "repl_{{type}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[$interval]) or \nirate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[5m])",
     "legendFormat": "ttl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[$interval]) or \nirate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[$interval]) or \nirate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_extra_info_page_faults_total{instance=\"$host\"}",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}