{
 "title": "192.168.42.102 Disk performance",
 "description": "Dashboard to view multiple servers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(node_disk_reads_completed_total{instance=~\"$host\", device!~\"dm-.+\"}, device)"
    }
   },
   { "name": "host", "label": "Host", "query": "192.168.42.102:9100" }
  ]
 },
 "panels": [
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_read_time_seconds_total{device=~\"$device\",instance=~\"$host.*\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host.*\"}[$interval])) or\n(irate(node_disk_read_time_seconds_total{device=~\"$device\",instance=~\"$host.*\"}[5m]) / irate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host.*\"}[5m]))",
     "legendFormat": "Read: {{device}}"
    },
    {
     "expr": "(rate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host.*\"}[$interval]) / \nrate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host.*\"}[$interval])) or \n(irate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host.*\"}[5m]) / \nirate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host.*\"}[5m]))",
     "legendFormat": "Write: {{device}}"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "iops", "label": "iops" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_reads_completed_total{instance=~\"$host\"}[5m]) or \nirate(node_disk_reads_completed_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "Read: {{device}}"
    },
    {
     "expr": "(rate(node_disk_writes_completed_total{instance=~\"$host\"}[5m]) or \nirate(node_disk_writes_completed_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "Write: {{device}}"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_read_bytes_total{instance=~\"$host\"}[5m]) or \nirate(node_disk_read_bytes_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "Read: {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$host\"}[5m]) or \nirate(node_disk_written_bytes_total{instance=~\"$host\"}[5m])",
     "legendFormat": "Write: {{device}}"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$host\"}[5m])/1000 or irate(node_disk_read_time_seconds_total{instance=~\"$host\"}[5m])/1000",
     "legendFormat": "Read: {{device}}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$host\"}[5m])/1000 or irate(node_disk_write_time_seconds_total{instance=~\"$host\"}[5m])/1000",
     "legendFormat": "Write: {{device}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$host\"}[5m])/1000 or \nirate(node_disk_io_time_seconds_total{instance=~\"$host\"}[5m])/1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Operations Merge Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 + rate(node_disk_reads_merged_total{instance=~\"$host\"}[5m]) / rate(node_disk_reads_completed_total{instance=~\"$host\"}[5m])) or (1 + irate(node_disk_reads_merged_total{instance=~\"$host\"}[5m]) / irate(node_disk_reads_completed_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "Read Ration: {{device}}"
    },
    {
     "expr": "(1 + rate(node_disk_writes_merged_total{instance=~\"$host\"}[5m]) / rate(node_disk_writes_completed_total{instance=~\"$host\"}[5m])) or (1 + irate(node_disk_writes_merged_total{instance=~\"$host\"}[5m]) / irate(node_disk_writes_completed_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "Write Ratio: {{device}}"
    }
   ]
  },
  {
   "title": "Disk IO Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$host\"}[5m]) / rate(node_disk_reads_completed_total{instance=~\"$host\"}[5m]) or irate(node_disk_read_bytes_total{instance=~\"$host\"}[5m]) / irate(node_disk_reads_completed_total{instance=~\"$host\"}[5m]) ",
     "legendFormat": "Read size: {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$host\"}[5m]) * 512 / rate(node_disk_writes_completed_total{instance=~\"$host\"}[5m]) or irate(node_disk_written_bytes_total{instance=~\"$host\"}[5m]) / irate(node_disk_writes_completed_total{instance=~\"$host\"}[5m]) ",
     "legendFormat": "Write size: {{device}}"
    }
   ]
  }
 ]
}