{
 "title": "ReplicaSet",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "instance",
    "query": "192.168.42.100,192.168.42.101,192.168.42.102"
   },
   { "name": "replSet", "label": "Replica Set", "query": "mongo_repl" },
   { "name": "port", "label": "mongo metric port", "query": "9216" },
   { "name": "interval", "label": "interval", "query": "1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "ReplicaSet State 192.168.42.100",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{instance=\"192.168.42.100:9216\",job=\"mongo_repl\",set=\"dojo\"}"
    }
   ]
  },
  {
   "title": "ReplicaSet State 192.168.42.101",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{instance=\"192.168.42.101:9216\",job=\"mongo_repl\",set=\"dojo\"}"
    }
   ]
  },
  {
   "title": "ReplicatSet State 192.168.42.102",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{instance=\"192.168.42.102:9216\",job=\"mongo_repl\",set=\"dojo\"}"
    }
   ]
  },
  {
   "title": "ReplSet Members",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{instance=\"192.168.42.100:9216\",job=\"mongo_repl\",set=\"dojo\"}"
    }
   ]
  },
  {
   "title": "ReplSet Members",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{instance=\"192.168.42.101:9216\",job=\"mongo_repl\",set=\"dojo\"}"
    }
   ]
  },
  {
   "title": "ReplSet Members",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{instance=\"192.168.42.102:9216\",job=\"mongo_repl\",set=\"dojo\"}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - mongodb_mongod_replset_member_election_date{instance=\"192.168.42.100:9216\"}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - mongodb_mongod_replset_member_election_date{instance=\"192.168.42.101:9216\"}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - mongodb_mongod_replset_member_election_date{instance=\"192.168.42.102:9216\"}"
    }
   ]
  },
  {
   "title": "ReplSet Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=\"192.168.42.100:9216\",name=\"192.168.42.101:27017\"}",
     "legendFormat": "replication to 192.168.42.101"
    },
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=\"192.168.42.100:9216\",name=\"192.168.42.102:27017\"}",
     "legendFormat": "replication to 192.168.42.102"
    }
   ]
  },
  {
   "title": "ReplSet Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=\"192.168.42.101:9216\",name=\"192.168.42.100:27017\"}",
     "legendFormat": "replication to 192.168.42.100"
    },
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=\"192.168.42.101:9216\",name=\"192.168.42.102:27017\"}",
     "legendFormat": "replication to 192.168.42.102"
    }
   ]
  },
  {
   "title": "ReplSet lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=\"192.168.42.102:9216\",name=\"192.168.42.100:27017\"}",
     "legendFormat": "replication to 192.168.42.100"
    },
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=\"192.168.42.102:9216\",name=\"192.168.42.101:27017\"}",
     "legendFormat": "replication to 192.168.42.101"
    }
   ]
  },
  {
   "title": "CPU 192.168.42.100",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=~\"192.168.42.100:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU 192.168.42.101",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=~\"192.168.42.101:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU 192.168.42.102",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=~\"192.168.42.102:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.42.100:9100\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.42.100:9100\"} - node_memory_MemFree_bytes{instance=\"192.168.42.100:9100\"} - (node_memory_Cached_bytes{instance=\"192.168.42.100:9100\"} + node_memory_Buffers_bytes{instance=\"192.168.42.100:9100\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"192.168.42.100:9100\"} + node_memory_Buffers_bytes{instance=\"192.168.42.100:9100\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"192.168.42.100:9100\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"192.168.42.100:9100\"} - node_memory_SwapFree_bytes{instance=\"192.168.42.100:9100\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.42.101:9100\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.42.101:9100\"} - node_memory_MemFree_bytes{instance=\"192.168.42.101:9100\"} - (node_memory_Cached_bytes{instance=\"192.168.42.101:9100\"} + node_memory_Buffers_bytes{instance=\"192.168.42.101:9100\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"192.168.42.101:9100\"} + node_memory_Buffers_bytes{instance=\"192.168.42.101:9100\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"192.168.42.101:9100\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"192.168.42.101:9100\"} - node_memory_SwapFree_bytes{instance=\"192.168.42.101:9100\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.42.102:9100\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.42.102:9100\"} - node_memory_MemFree_bytes{instance=\"192.168.42.102:9100\"} - (node_memory_Cached_bytes{instance=\"192.168.42.102:9100\"} + node_memory_Buffers_bytes{instance=\"192.168.42.102:9100\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"192.168.42.102:9100\"} + node_memory_Buffers_bytes{instance=\"192.168.42.102:9100\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"192.168.42.102:9100\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"192.168.42.102:9100\"} - node_memory_SwapFree_bytes{instance=\"192.168.42.102:9100\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"192.168.42.100:9216\", type!~\"(command|getmore|query)\"}[$interval]) or \nirate(mongodb_mongod_op_counters_repl_total{instance=\"192.168.42.100:9216\", type!~\"(command|getmore|query)\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"192.168.42.101:9216\", type!~\"(command|getmore|query)\"}[$interval]) or \nirate(mongodb_mongod_op_counters_repl_total{instance=\"192.168.42.101:9216\", type!~\"(command|getmore|query)\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"192.168.42.102:9216\", type!~\"(command|getmore|query)\"}[$interval]) or \nirate(mongodb_mongod_op_counters_repl_total{instance=\"192.168.42.102:9216\", type!~\"(command|getmore|query)\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Oplog Recovery Window",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-mongodb_mongod_replset_oplog_tail_timestamp{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "Now to End"
    },
    {
     "expr": "mongodb_mongod_replset_oplog_head_timestamp{instance=\"192.168.42.100:9216\"} - mongodb_mongod_replset_oplog_tail_timestamp{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "OpLog Range"
    }
   ]
  },
  {
   "title": "Oplog Recovery Window",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-mongodb_mongod_replset_oplog_tail_timestamp{instance=\"192.168.42.101:9216\"}",
     "legendFormat": "Now to End"
    },
    {
     "expr": "mongodb_mongod_replset_oplog_head_timestamp{instance=\"192.168.42.101:9216\"} - mongodb_mongod_replset_oplog_tail_timestamp{instance=\"192.168.42.101:9216\"}",
     "legendFormat": "OpLog Range"
    }
   ]
  },
  {
   "title": "Oplog Recovery Window",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-mongodb_mongod_replset_oplog_tail_timestamp{instance=\"192.168.42.102:9216\"}",
     "legendFormat": "Now to End"
    },
    {
     "expr": "mongodb_mongod_replset_oplog_head_timestamp{instance=\"192.168.42.102:9216\"} - mongodb_mongod_replset_oplog_tail_timestamp{instance=\"192.168.42.102:9216\"}",
     "legendFormat": "OpLog Range"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=\"192.168.42.101:9216\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=\"192.168.42.102:9216\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Elections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(mongodb_mongod_replset_member_election_date{instance=\"192.168.42.100:9216\"}[$interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Elections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(mongodb_mongod_replset_member_election_date{instance=\"192.168.42.101:9216\"}[$interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Elections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(mongodb_mongod_replset_member_election_date{instance=\"192.168.42.102:9216\"}[$interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Member State Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Member State Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Member State Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_ping_ms{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_ping_ms{instance=\"192.168.42.101:9216\"}",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_ping_ms{instance=\"192.168.42.102:9216\"}",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_last_heartbeat{instance=\"192.168.42.100:9216\", state=\"PRIMARY\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_last_heartbeat{instance=\"192.168.42.101:9216\", state=\"PRIMARY\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_last_heartbeat{instance=\"192.168.42.102:9216\", state=\"PRIMARY\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=\"192.168.42.100:9216\"}[$interval]) or \nirate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=\"192.168.42.100:9216\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=\"192.168.42.100:9216\"}[$interval]) or \nirate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=\"192.168.42.100:9216\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_ops_total{instance=\"192.168.42.100:9216\"}[$interval]) or \nirate(mongodb_mongod_metrics_repl_apply_ops_total{instance=\"192.168.42.100:9216\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=\"192.168.42.101:9216\"}[$interval]) or \nirate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=\"192.168.42.101:9216\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=\"192.168.42.101:9216\"}[$interval]) or \nirate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=\"192.168.42.101:9216\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_ops_total{instance=\"192.168.42.101:9216\"}[$interval]) or \nirate(mongodb_mongod_metrics_repl_apply_ops_total{instance=\"192.168.42.101:9216\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=\"192.168.42.102:9216\"}[$interval]) or \nirate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=\"192.168.42.102:9216\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=\"192.168.42.102:9216\"}[$interval]) or \nirate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=\"192.168.42.102:9216\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_ops_total{instance=\"192.168.42.102:9216\"}[$interval]) or \nirate(mongodb_mongod_metrics_repl_apply_ops_total{instance=\"192.168.42.102:9216\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_count{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_count{instance=\"192.168.42.101:9216\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_count{instance=\"192.168.42.102:9216\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{instance=\"192.168.42.101:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{instance=\"192.168.42.102:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=\"192.168.42.100:9216\"}[$interval]) or\nirate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=\"192.168.42.100:9216\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=\"192.168.42.100:9216\"}[$interval]) or\nirate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=\"192.168.42.100:9216\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=\"192.168.42.100:9216\"}[$interval]) or\nirate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=\"192.168.42.100:9216\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=\"192.168.42.101:9216\"}[$interval]) or\nirate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=\"192.168.42.101:9216\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=\"192.168.42.101:9216\"}[$interval]) or\nirate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=\"192.168.42.101:9216\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=\"192.168.42.101:9216\"}[$interval]) or\nirate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=\"192.168.42.101:9216\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=\"192.168.42.102:9216\"}[$interval]) or\nirate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=\"192.168.42.102:9216\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=\"192.168.42.102:9216\"}[$interval]) or\nirate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=\"192.168.42.102:9216\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=\"192.168.42.102:9216\"}[$interval]) or\nirate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=\"192.168.42.102:9216\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_size_bytes{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_max_size_bytes{instance=\"192.168.42.100:9216\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 123 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_size_bytes{instance=\"192.168.42.101:9216\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_max_size_bytes{instance=\"192.168.42.101:9216\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 123 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_size_bytes{instance=\"192.168.42.102:9216\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_max_size_bytes{instance=\"192.168.42.102:9216\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}