{
 "title": "ReplicaSet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "member_idx", "query": "mongo1,mongo2,mongo3" },
   { "name": "replSet", "label": "Replica Set", "query": "mongo_repl" },
   { "name": "port", "label": "mongo metric port", "query": "27017" },
   { "name": "interval", "label": "interval", "query": "1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "ReplicaSet State mongo1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_members_state{member_idx=\"mongo1:27017\"}"
    }
   ]
  },
  {
   "title": "ReplicaSet State mongo2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_members_state{member_idx=\"mongo2:27017\"}"
    }
   ]
  },
  {
   "title": "ReplicaSet State mongo3",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_members_state{member_idx=\"mongo3:27017\"}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - mongodb_rs_members_electionDate{member_idx=\"mongo1:27017\"}/1000"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - mongodb_rs_members_electionDate{member_idx=\"mongo2:27017\"}/1000"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - mongodb_rs_members_electionDate{member_idx=\"mongo3:27017\"}/1000"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{job=\"mongo_repl\", legacy_op_type!~\"(command|getmore|query)\"}[$interval]) or \nirate(mongodb_ss_opcounters{job=\"mongo_repl\", legacy_op_type!~\"(command|getmore|query)\"}[5m])",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Member State Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_rs_members_uptime{member_idx=\"mongo1:27017\"}",
     "legendFormat": "{{member_idx}} - {{member_state}}"
    }
   ]
  },
  {
   "title": "Member State Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_rs_members_uptime{member_idx=\"mongo2:27017\"}",
     "legendFormat": "{{member_idx}} - {{member_state}}"
    }
   ]
  },
  {
   "title": "Member State Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_rs_members_uptime{member_idx=\"mongo3:27017\"}",
     "legendFormat": "{{member_idx}} - {{member_state}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_rs_members_pingMs{instance=\"mongo-exporter:9216\", member_idx=\"mongo1:27017\"}",
     "legendFormat": "{{instance}} - {{member_idx}}"
    },
    {
     "expr": "mongodb_rs_members_pingMs{instance=\"mongo-exporter:9216\", member_idx=\"mongo2:27017\"}",
     "legendFormat": "{{instance}} - {{member_idx}}"
    },
    {
     "expr": "mongodb_rs_members_pingMs{instance=\"mongo-exporter:9216\", member_idx=\"mongo3:27017\"}",
     "legendFormat": "{{instance}} - {{member_idx}}"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(mongodb_rs_members_lastHeartbeatRecv{member_idx=\"mongo1:27017\"}/1000)",
     "legendFormat": "mongo1"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(mongodb_rs_members_lastHeartbeatRecv{member_idx=\"mongo2:27017\"}/1000)",
     "legendFormat": "mongo2"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(mongodb_rs_members_lastHeartbeatRecv{member_idx=\"mongo3:27017\"}/1000)",
     "legendFormat": "mongo3"
    }
   ]
  },
  {
   "title": "Oplog Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_repl_preload_docs_num{job=\"mongo_repl\"}[$interval]) or \nirate(mongodb_ss_metrics_repl_preload_docs_num{job=\"mongo_repl\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_ss_metrics_repl_preload_indexes_num{job=\"mongo_repl\"}[$interval]) or \nirate(mongodb_ss_metrics_repl_preload_indexes_num{job=\"mongo_repl\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_ss_metrics_repl_apply_ops{job=\"mongo_repl\"}[$interval]) or \nirate(mongodb_ss_metrics_repl_apply_ops{job=\"mongo_repl\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_repl_buffer_count{job=\"mongo_repl\"}[5m])",
     "legendFormat": "Buffer count"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_ss_metrics_repl_network_getmores_totalMillis{job=\"mongo_repl\"}",
     "legendFormat": "GetMores"
    }
   ]
  },
  {
   "title": "Oplog Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_repl_preload_docs_totalMillis{job=\"mongo_repl\"}[$interval]) or\nirate(mongodb_ss_metrics_repl_preload_docs_totalMillis{job=\"mongo_repl\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_ss_metrics_repl_preload_indexes_totalMillis{job=\"mongo_repl\"}[$interval]) or\nirate(mongodb_ss_metrics_repl_preload_indexes_totalMillis{job=\"mongo_repl\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_ss_metrics_repl_apply_batches_totalMillis{job=\"mongo_repl\"}[$interval]) or\nirate(mongodb_ss_metrics_repl_apply_batches_totalMillis{job=\"mongo_repl\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_ss_metrics_repl_buffer_sizeBytes{job=\"mongo_repl\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mongodb_ss_metrics_repl_buffer_maxSizeBytes{job=\"mongo_repl\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}